export const DISCORD_ON_EVENT_LISTENER_METADATA =
  'DISCORD_ON_EVENT_LISTENER_METADATA';

export const DISCORD_ONCE_EVENT_LISTENER_METADATA =
  'DISCORD_ONCE_EVENT_LISTENER_METADATA';

export const DISCORD_TOKEN = 'DISCORD_TOKEN';
