export const LINE_ON_EVENT_LISTENER_METADATA =
  'LINE_ON_EVENT_LISTENER_METADATA';

export const LINE_ACCESS_TOKEN = 'LINE_ACCESS_TOKEN';

export const LINE_SECRET = 'LINE_SECRET';

export const INTERNAL_EVENT_EMITTER = 'INTERNAL_EVENT_EMITTER';
